### ISSUE TITLE
Breaks JSON-LD Playground T_T

### ISSUE THREAD

**Issue by BigBlueHat** [Treora/selector-extension#3]
https://json-ld.org/playground/

I've not yet sorted out why/how exactly...but disabling this extension brought the JSON-LD Playground back to life.

**Comment by Treora** [comment]
Apologies for the inconvenience, thanks for reporting, fixed it now.

Apparently setting `window.onload` in a content script in Firefox will override the website's own value for it, while in Chromium it does not. (the `window` object is largely shared with the page, but not completely, in ways I have yet to fully grasp)

The obvious solution is using `window.addEventListener('load', .....)`, which is preferable anyhow.
